### ISSUE TITLE
NLP on dangling parts

### ISSUE THREAD

**Issue by joeflack4** [loinc/comp-loinc#119]
## Overview
There are a substantial amount of parts with no parent or child. We would like to see if they might actually fit in somewhere in the / a hierarchy, either amongst themselves, or within the main LOINC hierarchy(s).

## Sub-tasks
- [x] 1. Write dangling parts to TSV
- [ ] 2. Connect amongst themselves
- [ ] 3. Connect with existing LOINC hierarchy
- [ ] 4. Optional: Data visualization

## Additional notes
For 2 & 3, output will be some relational flat file that shows proposed relationships, possibly also with confidence values.
