### ISSUE TITLE
MVP stable / basic pipeline

### ISSUE THREAD

**Issue by joeflack4** [loinc/comp-loinc#49]
## Overview
Not everything has to be perfect, but just ensure we have a way to run the pipeline, at least for the core, most important output(s), in a simple way.

## Sub-tasks
- [x] Ensure code for core build / output(s) runs without error @ShahimEssaid 
- [x] Basic CLI @ShahimEssaid 
- [ ] Basic `make all` @joeflack4 or @ShahimEssaid 

Related, but not in scope for this issue:
- #50 @joeflack4

**Comment by joeflack4** [comment]
@ShahimEssaid I think this is is roughly completed.

I think we do want some kind of `make all`, which is all that remains.
