### ISSUE TITLE
Joe: get up to speed

### ISSUE THREAD

**Issue by joeflack4** [loinc/comp-loinc#57]
## Overview
Joe has a lot of getting up-to-speed to do.

## Sub-tasks
- [x] Look through and understand release files
- [x] Read thoroughly through relevant [LOINC docs](https://loinc.org/kb/users-guide/).
- [x] Read through and understand codebase

**Comment by joeflack4** [comment]
I haven't done 100% of this, but I've basically done a reverse 80/20; I've done 80% of each of these. The longtail of learning will be ongoing.
