### ISSUE TITLE
`--fast-run` updates

### ISSUE THREAD

**Issue by joeflack4** [loinc/comp-loinc#77]
## Sub-tasks
- [ ] #76 
- [ ] Possibly allow optional integer allowing to stipulate how many entities/rows/iterations the 'fast run' represents (I think currently is 1000)
- [ ] Better logging to give faster feedback
- [ ] Shahim: Current implementation is very hacky

**Comment by joeflack4** [comment]
FYI: Keep it limited to just LinkML entities (rather than expand to the graph)

[Shahim](https://github.com/loinc/comp-loinc/issues/76#issuecomment-2357034571):
> It's also limited to the creation of the entities and should probably stay that way. It won't be useful to add this to the graph loading since needed information will be missing with an incomplete load. But, that part doesn't take too long anyway.
