### ISSUE TITLE
Pickling

### ISSUE THREAD

**Issue by joeflack4** [loinc/comp-loinc#79]
## Overview
We currently have ways to pickle / cache the `loinclib` `networkx` graph via a hidden param, but it is not fully implemented.

## Sub-tasks
- `loinclib`
  - [ ] Finish whatever is needed for implementation
  - [ ] Config / CLI for multiple LOINC versions
- `comp_loinc`
  - [ ] Consider whether any caching options make sense here as well
