### ISSUE TITLE
Tests: Create static inputs

### ISSUE THREAD

**Issue by joeflack4** [loinc/comp-loinc#92]
## Overview
_Update 2024/12_: We've determined that `--fast-run` is deterministic, and have instead tweaked that to be more thorough, and are using that instead of this. Static inputs would be nicer, but it is not so important now.

Would be nice to have alternative variations for all test input files. These should be smaller so that tests run faster. The data should also be synthetic to avoid any licensing issues.

## Sub-tasks
- [ ] 1. **Simple inputs**: Create synthetic test inputs that have a small number of rows.
- [ ] 2. **Config**: Set up so that when test is run, it uses these inputs instead of what's listed in the `comploinc_config.yaml`
- [ ] 3. **Updated inputs**: Upgrade inputs for internal consistency

## 3. Upgrade inputs for internal consistency
Ideally, the synthetic terms and properties between the files should/would be linked so that the output makes more sense and more sensible tests can be run. What I mean by this is that the synthetic part terms created in one file should be shown in other files, synthetic LOINC terms should appear in the synthetic LOINC release, as well as the LOINC tree, etc. SNOMED-Ontology synthetic terms should be found both in synthetic SNOMED and LOINC. This might be a tall order though; so maybe could leave this requirement out for the first iteration.

**Comment by joeflack4** [comment]
### Update
I started working on this in:
- #96 

However, I closed that because I found that `--fast-run` was deterministic, other than the order, so I thought it'd save time just to use the `--fast-run` outputs:
- #110
  - #112 
  - #115 
- #114 (order is the only thing that's different; not content)

However again, I needed to update the tests (#115) to account for the lower `n` from using `--fast-run`. But what I observed is that because of this lower `n`, because the code is of course set up to process the inputs linearly row by row, the outputs of `--fast-run` aren't necessarily going to have a rich structure. Indeed, they are a bit flatter, and I've had to set very low `n` for expected results in several tests, primarily for the SNOMED output(s). I think this lowers the effectiveness of the test.

Possible solutions:
a. Find a way to increase the size of SNOMED outputs when running `--fast-run`
  - This isn't actually easy. This is determined, for some reason, not simply by the `--fast-run` n rows limit set within the SNOMED loader, but due to some interaction with LOINC content (mappings, I think), if the n row limit for LOINC is low, that will also affect the output for SNOMED.
  - This is also not guaranteed to gives us a rich structure to test.
b. Create static inputs (#92)
  - This will ensure that we can create these inputs with intentionality and ensure we have a rich, representative structure to test.
  - Disadvantage: Takes time to implement.

**Comment by joeflack4** [comment]
_Update 2024/12_: We've determined that `--fast-run` is deterministic, and have instead tweaked that to be more thorough, and are using that instead of this. Static inputs would be nicer, but it is not so important now.
