### ISSUE TITLE
GH Actions: Run pipeline (full build release)

### ISSUE THREAD

**Issue by joeflack4** [loinc/comp-loinc#93]
## Sub-tasks
- [ ] 1. **Approval**: Seek possible approval to upload 1 or more outputs in GH releases
- [ ] 2. **Private releases** If not (1), or if (1) is approved for a subset, release outputs in a private way
  - I don't know if there's a standard way to release private outputs in a public repository.
  - This may just involve having a separate, private fork just for releases.
- [ ] 3. **GH Action**: Set up a new one
  - Involves downloading and unzipping inputs

## Related
- #50

**Comment by joeflack4** [comment]
Closing this because we are running a small portion of the build using `--fast-run`, and that is probably sufficient.
